---
title: "Introduction II"
---

# Handling Data Structures in RStudio

## Learning objectives

By the end of this tutorial, you will be able to:

1. Set your working directory on Mac and Windows
2. Import a .csv file into RStudio
3. Understand the structure of a data frame (rows and columns)
4. Filter data using both numeric and categorical variables
5. Combine multiple conditions with logical operators to perform further filtering of data
6. Export data back into a .csv file

These objectives, combined with those from last week, serve as a gateway to learning RStudio and building a strong foundation. Let us begin!

## Setting the Working Directory to Datasets

:::{.callout-warning}
Before we do anything - make sure to have downloaded the dataset for this computer session by clicking [**[HERE]**](). There are three datasets:

1. `Primary Schools in Ealing.csv`: This comma separated values (CSV) file contains the data needed to follow today's tutorial.
2 `Open Street Drains in Accra`: This is zipped folder containing images of stormwater drainage infrastructure in Accra annotated with key information to created a data frame. It will be needed in part one of **Task 1**.
3. `Prevalence of Soil Transmitted Helminths in Africa.csv`: This dataset contains point locations for villages across sub-Saharan Africa. It will be needed in part two of **Task 1**.

**Instructions**
In your computer, do the following:

1. Create a new folder on your desktop and rename the folder **GEOG0186**
2. Next, create a new sub-folder within **GEOG0186** and rename it as **Week 2**.
3. From the downloaded folder **Dataset for Week 2**, make sure to unzip and transfer **ALL** the datasets directly to the **Week 2** folder.
:::

This part is probably the most important section of this tutorial.We are going to learn how to set the **Work Directory**. This basically refers to us connecting the RStudio to the folder containing our dataset that we want to import and analyse. 

Doing this allows the user to tell RStudio to open data from a folder located somewhere in our computer using something called the **Path Location**. 

The **Path Location** specifies the whereabouts of the data file(s) stored within a computer. Setting your directory in RStudio, **in code**, beforehand makes life incredibly easier (than the usual point-and-click approach) in terms of finding, importing, exporting and saving data in and out of RStudio.

To illustrate what a **Path Location** is – suppose on my desktop's dashboard on a Mac/Windows there is a folder called **GEOG0186**, and within that folder, exists another folder called **Week 2**. Finally, suppose a comma separated value (.csv) data file called `Primary Schools in Ealing.csv` is store in this folder i.e., **Week 2**. If via RStudio you want to open this CSV data file located in within the **Week 2** folder. You will need to first set the path to **Week 2** in RStudio using the `setwd()` function.

### Setting the Path Location on MAC


### Setting the Path Location on Windows