<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Week 3: Examining Data I</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03-handling_data_structures.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e8fb9d25728d58bfeac61b497e4a6629.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-57a92833092fd6dc0d7710b6bdfff9c5.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-26a71f2b824b3e323bb4b2f87a684bec.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-22f3b3604dd1545f9653ae63cc55d477.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link href="site_libs/vembedr-0.1.5/css/vembedr.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="assets/all_css/styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-basic_building_blocks.html">Core Content</a></li><li class="breadcrumb-item"><a href="./04-frequency_distribution.html">Week 3: Examining Data I</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
      <a href="https://www.ucl.ac.uk/module-catalogue/modules/foundations-of-geography-1-GEOG0186" class="sidebar-logo-link">
      <img src="./assets/all_images/sidebar_cosmetics/00_ucl_logo.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/UCLPG-MSC-SGDS/GEOG0186" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
    <div id="quarto-search" class="quarto-navigation-tool px-1" title="Search"></div>
</div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Module Overview</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-module_overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Getting Started</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-what_is_rstudio.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">What is RStudio (or R)?</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Core Content</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-basic_building_blocks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 1: Introduction I</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-handling_data_structures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Week 2: Introduction II</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-frequency_distribution.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Week 3: Examining Data I</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#frequency-distribution" id="toc-frequency-distribution" class="nav-link active" data-scroll-target="#frequency-distribution"><span class="header-section-number">1</span> Frequency Distribution</a>
  <ul>
  <li><a href="#learning-outcomes" id="toc-learning-outcomes" class="nav-link" data-scroll-target="#learning-outcomes"><span class="header-section-number">1.1</span> Learning outcomes</a></li>
  <li><a href="#short-lecture-videos-optional" id="toc-short-lecture-videos-optional" class="nav-link" data-scroll-target="#short-lecture-videos-optional"><span class="header-section-number">1.2</span> Short Lecture Videos [OPTIONAL]</a>
  <ul class="collapse">
  <li><a href="#what-is-statistics-and-data-in-general" id="toc-what-is-statistics-and-data-in-general" class="nav-link" data-scroll-target="#what-is-statistics-and-data-in-general"><span class="header-section-number">1.2.1</span> What is statistics and data in general?</a></li>
  </ul></li>
  <li><a href="#analysing-air-pollution-data-in-barcelona" id="toc-analysing-air-pollution-data-in-barcelona" class="nav-link" data-scroll-target="#analysing-air-pollution-data-in-barcelona"><span class="header-section-number">1.3</span> Analysing air pollution data in Barcelona</a>
  <ul class="collapse">
  <li><a href="#setting-working-directory-reading-a-csv-length-001354" id="toc-setting-working-directory-reading-a-csv-length-001354" class="nav-link" data-scroll-target="#setting-working-directory-reading-a-csv-length-001354"><span class="header-section-number">1.3.1</span> Setting Working Directory &amp; Reading a CSV (Length: 00:13:54)</a></li>
  </ul></li>
  <li><a href="#frequency-distributions" id="toc-frequency-distributions" class="nav-link" data-scroll-target="#frequency-distributions"><span class="header-section-number">1.4</span> Frequency Distributions</a>
  <ul class="collapse">
  <li><a href="#using-the-cut-seq-table-functions-length-001756" id="toc-using-the-cut-seq-table-functions-length-001756" class="nav-link" data-scroll-target="#using-the-cut-seq-table-functions-length-001756"><span class="header-section-number">1.4.1</span> Using the <code>cut()</code>, <code>seq()</code> &amp; <code>table()</code> functions (Length: 00:17:56)</a></li>
  <li><a href="#computing-the-frequency-distribution-table-length-002753" id="toc-computing-the-frequency-distribution-table-length-002753" class="nav-link" data-scroll-target="#computing-the-frequency-distribution-table-length-002753"><span class="header-section-number">1.4.2</span> Computing the Frequency Distribution Table (Length: 00:27:53)</a></li>
  <li><a href="#graphical-representation-of-frequency-data" id="toc-graphical-representation-of-frequency-data" class="nav-link" data-scroll-target="#graphical-representation-of-frequency-data"><span class="header-section-number">1.4.3</span> Graphical Representation of Frequency Data</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/UCLPG-MSC-SGDS/GEOG0186/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-basic_building_blocks.html">Core Content</a></li><li class="breadcrumb-item"><a href="./04-frequency_distribution.html">Week 3: Examining Data I</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Week 3: Examining Data I</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="frequency-distribution" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Frequency Distribution</h1>
<section id="learning-outcomes" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="learning-outcomes"><span class="header-section-number">1.1</span> Learning outcomes</h2>
<p>By the end of this tutorial, you will be able to:</p>
<ol type="1">
<li>Understand frequency distributions</li>
<li>How to categorise continuous measurements in classes/categorise using the <code>cut()</code></li>
<li>How to compute a frequency table</li>
<li>How to provide an interpretation to such outputs</li>
<li>How to translate a frequency distribution table into a histogram and cumulative frequency plot</li>
</ol>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>Before we do anything - make sure to have downloaded the dataset for this computer session by clicking <a href="https://github.com/UCLPG-MSC-SGDS/GEOG0186/raw/main/datasets/Dataset%20for%20Week%203.zip"><strong>[HERE]</strong></a>. It contains the file <code>Barcelona_Air_Pollution_data.csv</code> - this comma separated values (CSV) file contains the data needed to follow today’s tutorial.</p>
<p><strong>Instructions</strong> In your computer, do the following:</p>
<ol type="1">
<li>Create a new folder on your desktop and rename the folder <strong>GEOG0186</strong></li>
<li>Next, create a new sub-folder within <strong>GEOG0186</strong> and rename it as <strong>Week 3</strong>.</li>
<li>From the downloaded folder <strong>Dataset for Week 3</strong>, make sure to unzip and transfer <strong>ALL</strong> the datasets directly to the <strong>Week 3</strong> folder.</li>
</ol>
</div>
</div>
</section>
<section id="short-lecture-videos-optional" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="short-lecture-videos-optional"><span class="header-section-number">1.2</span> Short Lecture Videos [OPTIONAL]</h2>
<p>Jump straight to the coding exercise by clicking <a href="https://uclpg-msc-sgds.github.io/GEOG0186/04-frequency_distribution.html#analysing-air-pollution-data-in-barcelona"><strong>HERE</strong></a> if you want to skip this section!</p>
<section id="what-is-statistics-and-data-in-general" class="level3" data-number="1.2.1">
<h3 data-number="1.2.1" class="anchored" data-anchor-id="what-is-statistics-and-data-in-general"><span class="header-section-number">1.2.1</span> What is statistics and data in general?</h3>
<p><strong>Definition 1</strong>: Statistics is a branch in the mathematical sciences that pertains to the collection, analysis, interpretation, and graphical presentation of data. The best thing about statistics is that it’s a highly applied branch of science which is applicable to many areas such as social science, politics, health (e.g., epidemiology), business &amp; finance, environmental sciences and geography.</p>
<p>Statistics is broadly split into two main areas:</p>
<ol type="1">
<li>Descriptive statistics, which focuses on describing the visible characteristics about a dataset</li>
<li>Inferential statistics is more research-based, which focuses on making predictions (rather than stating facts) and testing hypothesis about a phenomenon.</li>
</ol>
<p><strong>Definition 2</strong>: A variable is any characteristics, numbered value, or quantity that can be measured or counted. A variable can also be referred to a data Item. A variable can be broadly classified as discrete, continuous or categorical variable.</p>
<p>We have provided two videos: the first which broadly explains why statistics as a subject is important; and the second explains in much details what statistics is as a subject, and what are the various data types.</p>
<p><strong>[Theory] Why is statistics important? (Length: 13:21 minutes)</strong></p>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<div class="vembedr" align="center">
<div>
<iframe src="https://www.youtube.com/embed/BTQihTqIR8Y" width="711" height="400" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
<p>Watch on YouTube <a href="https://youtu.be/BTQihTqIR8Y">[<strong>LINK</strong>]</a></p>
<p><strong>[Theory] What is statistics, and the types of variables? (Length: 31:17 minutes)</strong></p>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<div class="vembedr" align="center">
<div>
<iframe src="https://www.youtube.com/embed/FJh6Cu-ATLM" width="711" height="400" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
<p>Watch on YouTube <a href="https://youtu.be/FJh6Cu-ATLM">[<strong>LINK</strong>]</a></p>
</section>
</section>
<section id="analysing-air-pollution-data-in-barcelona" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="analysing-air-pollution-data-in-barcelona"><span class="header-section-number">1.3</span> Analysing air pollution data in Barcelona</h2>
<p>We will focus on descriptive statistics as an introduction introducing everyone to the absolute basics. Descriptive statistics is all about knowing the <strong>data types</strong> and finding the <strong>distribution</strong>, <strong>central tendency</strong> and <strong>variability</strong> in such data set. These four key words may sound intimidating – but trust me – it is very easy! Let us learn how to perform the following aspect of finding the distribution in RStudio using the air pollution data for Barcelona.</p>
<section id="setting-working-directory-reading-a-csv-length-001354" class="level3" data-number="1.3.1">
<h3 data-number="1.3.1" class="anchored" data-anchor-id="setting-working-directory-reading-a-csv-length-001354"><span class="header-section-number">1.3.1</span> Setting Working Directory &amp; Reading a CSV (Length: 00:13:54)</h3>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<div class="vembedr" align="center">
<div>
<iframe src="https://www.youtube.com/embed/unkwigmi2xY" width="711" height="400" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
<p><a href="https://youtu.be/unkwigmi2xY">[<strong>Watch on YouTube</strong>]</a></p>
<p>Let us import for following dataset <code>Barcelona_Air_Pollution_data.csv</code> into RStudio, and call this object <code>air_ quality_data</code>.</p>
<p>Remember - always make sure that your work directory is linked to your folder containing your data.</p>
<p>For <strong>Windows</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"C:/Users/accountName/Desktop/GEOG0186/Week 3"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>For <strong>Macs</strong>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"/Users/accountName/Desktop/GEOG0186/Week 3"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, import you the data set as follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>air_quality_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Barcelona_Air_Pollution_data.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You use the command <code>View()</code> see the full data viewer, or <code>head()</code> to see the first five rows of the dataset.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># see imported dataset</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(air_quality_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(air_quality_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You will notice that the data contains six variables with the following information:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 23%">
<col style="width: 54%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Variable name</strong></th>
<th><strong>Variable Type</strong></th>
<th><strong>Information</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>Location</code></td>
<td>String/Text only</td>
<td>Name of location Eixample, Barcelona</td>
</tr>
<tr class="even">
<td><code>ReadingDate</code></td>
<td>Date</td>
<td>Data collection date for air quality measures</td>
</tr>
<tr class="odd">
<td><code>NO2_est</code></td>
<td>Continuous</td>
<td>Measurements for Nitrogen dioxide (NO<span class="math inline">\(_2\)</span>) (ppb)</td>
</tr>
<tr class="even">
<td><code>NO2_category</code></td>
<td>Categorical</td>
<td>Health impacts (negligible/low/moderate/high)</td>
</tr>
<tr class="odd">
<td><code>PM10_est</code></td>
<td>Continuous</td>
<td>Measurements for Particulate matter (PM<span class="math inline">\(_10\)</span>)</td>
</tr>
<tr class="even">
<td><code>PM10_category</code></td>
<td>Categorical</td>
<td>Health impacts (negligible/low/moderate)</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The <code>NO2_est</code>, for example, contains measurable items i.e., 718 observations for concentrations of ambient NO<span class="math inline">\(_2\)</span> in Eixample area of Barcelona, and hence its a continuous variable. These estimates have been categorised in accordance with their health dangers i.e., negligible (<span class="math inline">\(&lt;\)</span> 10 ppb); low (11-50 ppb);</p>
</div>
</div>
<p>Let us begin to analyse <code>NO2_est</code> and <code>NO2_category</code> with <strong>Frequency Distributions</strong></p>
</section>
</section>
<section id="frequency-distributions" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="frequency-distributions"><span class="header-section-number">1.4</span> Frequency Distributions</h2>
<section id="using-the-cut-seq-table-functions-length-001756" class="level3" data-number="1.4.1">
<h3 data-number="1.4.1" class="anchored" data-anchor-id="using-the-cut-seq-table-functions-length-001756"><span class="header-section-number">1.4.1</span> Using the <code>cut()</code>, <code>seq()</code> &amp; <code>table()</code> functions (Length: 00:17:56)</h3>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<div class="vembedr" align="center">
<div>
<iframe src="https://www.youtube.com/embed/HzlL_PVdy6A" width="711" height="400" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
<p><a href="https://youtu.be/HzlL_PVdy6A">[<strong>Watch on YouTube</strong>]</a></p>
<p>We use frequency distribution to analyse a set of continuous measurements. In data handling in this context, there are two outputs generated:</p>
<ol type="1">
<li><strong>Frequency</strong>, which tells us how often a particular result was obtained. From this we can calculate a percentage value which is referred to as <strong>Relative Frequency</strong>.<br>
</li>
<li><strong>Cumulative Frequency</strong>, this is a cumulative sum of the frequencies, which indicates how often a result was obtained that is less than a stated value in our collection of data. Again, from this we can also calculate a cumulative percentage value which is referred to as <strong>Cumulative Relative Frequency</strong>.</li>
</ol>
<p>Suppose, we want to assess the 718 observations for air pollutant Nitrogen Dioxide (NO<span class="math inline">\(_2\)</span>).</p>
<p>Let’s list the observations for Nitrogen Dioxide (NO<span class="math inline">\(_2\)</span>) in Barcelona:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>air_quality_data<span class="sc">$</span>NO2_est</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]  61  59  29  75  23  49  43  35  83  75  71  56  54  44  41  54  62  56
 [19]  26  42  71  86  85  52  56  45  68  86  69  71   4  82  43  51 114  43
 [37]  18  58  24  53  98  53 100  53  49  49  46  82  77  67  76  52  61  80
 [55]  77  70  56  49  42  73  64  33  71  72  13  37  26  46  84  72  65  76
 [73]  90  46  61  81  64  62  58  78  83  37 130  43  20  40 102  68  48  74
 [91]  52  43  80  71  42  84  44 121  41  66  44  50  38  75  41  45  48  63
[109]  53  63  63  46  34  87  75  74  36  69  46  15  80  75  83  95   5  65
[127]  21  84  68  32  45  73  53  31  85  91  73  46  25  75  70  84  68  65
[145]  58 113  62  60  55  69  82 100 105  47  60 103  53  34  39  22  21  71
[163]  85  56  73  61  24  44  47  49 100  64  91  79  42  32  33  84  43  61
[181]  63  49  80  46  58  45  37  66  60  75  35  75  48  43  57  67  54  38
[199]  22  51  69  51  64  32  20  52  42  65  69  47  40  34  34  51  57  43
[217]  52  86  53  43  54  75  56  62  41  84  41  22  83  76  51  31  50  65
[235]  76  77  61  50  75  49  47  65  78  39  51  49  75  45  50  69  86  75
[253]  89  68  84  90  90  56 106  63  90  57  38  86  22  39  19  61  44  63
[271]  52  42  46  56  40  69  62  42  54  17  49  84  34  89  65  53  78  67
[289]  55  61  39  82  58  15  63  76  55  80  56  79  72  58  74  27  93  40
[307]  40  58  79  81 123  84  37  87  38  49  91  50  59  69  57  68  53  38
[325]  51  78  71  72  55  70  56  63  85  78  64  23  84  43  46  33  59  58
[343]  47  64  68  89  76  86 116  52  34  63  40  41  72  87  37  62  38  68
[361]  88  39  59  77  75 112  44  40  90  37  66  61  65  50  79  79  36  36
[379]  12  86  40  62  63  71  53  30  44  76  41  62  77  80  62  86  37  48
[397]  80  55  56  49  84  48  49  84  60  76  28  77  41  57  55  51  54  54
[415]  11  43  38  86  30  23  78  29  80  16  48  90  44  42  50  54  45  42
[433]  70  49  67  73  60  42  99  97  77  46  52  24  75  30  70  81  53  17
[451]  63  59  44  41  67  56  58 111  43  47  49  58  36  72  36 103  63  77
[469]  65  42  42  79  41  24  59  50  46  55  77  91  54  70  73  53  80  53
[487]  72  67  95  57  87  39  73  56  34  56  75  74  72  42 119  55  43  69
[505]  55  52  77  63 108  43  61  47 117  80  61  67  78  49  42  35  58  54
[523]  36  84  56  72  70  40  59  71  56  49  66  52  48  60  54  73  66  67
[541]  70  93  65  60  13  83  49  42  62  63  50  46  54  94  73  54  74  54
[559]  10  71  41  17  75  55  54  54  83  47  49  90  76  89  83  43  76  67
[577]  75  88  59  60  34  36  63  42  59  71  73  73  40  74  53  56  99  46
[595]  46  64  37  20  84  86  47  57  54  56  78  73  65  72  37  57  38  46
[613]  43  57  98  32  98  53  86  59  63  42  60  60  51  58  59  83  67  42
[631]  74  62  84  67  49  76   2  44  51  69  69  87  49  18  73  66  81  78
[649]  82  69  50  36  71  60   7  50  49  60  55  25  58  76  69  61  88  45
[667]  59  59  91  61  81  81  83  71 108  99  46  69  38  54  59  16  75  81
[685]  35  63  65  71  57  53  58  37  39  43  64  76  56  72  87  74  74  77
[703]  46  87  53  60  47  10  61  35  36  60  71  45  47  79  37 123</code></pre>
</div>
</div>
<p>In a list format it is quite difficult to make head or tail on what observations appear frequently and its distribution. To summarise this - it will be helpful to classify the information into <strong>Classes</strong> and then obtain the <strong>Frequency</strong> and <strong>Cumulative Frequency</strong> in a table. We call this table a <strong>Frequency Table</strong>.</p>
<p>The minimum value for NO<span class="math inline">\(_2\)</span> is 2 and the maximum is 130. We can group the 718 observations into 13 <strong>classes</strong> using an interval of 10s e.g., <code>1-10, 11-20, 21-30, 31-40, 41-50, 51-60, 61-70, 71-80, 81-90, 91-100, 101-110, 111-120</code> and <code>121-130</code></p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>The way and manner you specify the classes and interval are up to you really. Here, 10 is being used for convenience.</p>
</div>
</div>
<p>The interval width is 10, we can generate sequence of number from 0 to 130, inclusively, to create the <strong>classes</strong> which in turn be used to group the 718 observations into 13 classes using the <code>seq()</code> and <code>cut()</code>.</p>
<p>For example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># using starting value as 0</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># using highest value as 130</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># using interval as 10</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="co">#  specify in this order the lower, highest, interval value in seq() function</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>classes <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">130</span>, <span class="dv">10</span>)</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>classes</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]   0  10  20  30  40  50  60  70  80  90 100 110 120 130</code></pre>
</div>
</div>
<p>The sequence of values are stored in the object called <code>classes</code>. Now, let us apply the <code>cut()</code> function to group the NO<span class="math inline">\(_2\)</span> data accordingly. We can do this by generating a new variable called <code>Groups</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># tell the cut() function to group NO2_est using the classes object</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>air_quality_data<span class="sc">$</span>Groups <span class="ot">&lt;-</span> <span class="fu">cut</span>(air_quality_data<span class="sc">$</span>NO2_est, <span class="at">breaks=</span>classes)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>air_quality_data<span class="sc">$</span>Groups</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] (60,70]   (50,60]   (20,30]   (70,80]   (20,30]   (40,50]   (40,50]  
  [8] (30,40]   (80,90]   (70,80]   (70,80]   (50,60]   (50,60]   (40,50]  
 [15] (40,50]   (50,60]   (60,70]   (50,60]   (20,30]   (40,50]   (70,80]  
 [22] (80,90]   (80,90]   (50,60]   (50,60]   (40,50]   (60,70]   (80,90]  
 [29] (60,70]   (70,80]   (0,10]    (80,90]   (40,50]   (50,60]   (110,120]
 [36] (40,50]   (10,20]   (50,60]   (20,30]   (50,60]   (90,100]  (50,60]  
 [43] (90,100]  (50,60]   (40,50]   (40,50]   (40,50]   (80,90]   (70,80]  
 [50] (60,70]   (70,80]   (50,60]   (60,70]   (70,80]   (70,80]   (60,70]  
 [57] (50,60]   (40,50]   (40,50]   (70,80]   (60,70]   (30,40]   (70,80]  
 [64] (70,80]   (10,20]   (30,40]   (20,30]   (40,50]   (80,90]   (70,80]  
 [71] (60,70]   (70,80]   (80,90]   (40,50]   (60,70]   (80,90]   (60,70]  
 [78] (60,70]   (50,60]   (70,80]   (80,90]   (30,40]   (120,130] (40,50]  
 [85] (10,20]   (30,40]   (100,110] (60,70]   (40,50]   (70,80]   (50,60]  
 [92] (40,50]   (70,80]   (70,80]   (40,50]   (80,90]   (40,50]   (120,130]
 [99] (40,50]   (60,70]   (40,50]   (40,50]   (30,40]   (70,80]   (40,50]  
[106] (40,50]   (40,50]   (60,70]   (50,60]   (60,70]   (60,70]   (40,50]  
[113] (30,40]   (80,90]   (70,80]   (70,80]   (30,40]   (60,70]   (40,50]  
[120] (10,20]   (70,80]   (70,80]   (80,90]   (90,100]  (0,10]    (60,70]  
[127] (20,30]   (80,90]   (60,70]   (30,40]   (40,50]   (70,80]   (50,60]  
[134] (30,40]   (80,90]   (90,100]  (70,80]   (40,50]   (20,30]   (70,80]  
[141] (60,70]   (80,90]   (60,70]   (60,70]   (50,60]   (110,120] (60,70]  
[148] (50,60]   (50,60]   (60,70]   (80,90]   (90,100]  (100,110] (40,50]  
[155] (50,60]   (100,110] (50,60]   (30,40]   (30,40]   (20,30]   (20,30]  
[162] (70,80]   (80,90]   (50,60]   (70,80]   (60,70]   (20,30]   (40,50]  
[169] (40,50]   (40,50]   (90,100]  (60,70]   (90,100]  (70,80]   (40,50]  
[176] (30,40]   (30,40]   (80,90]   (40,50]   (60,70]   (60,70]   (40,50]  
[183] (70,80]   (40,50]   (50,60]   (40,50]   (30,40]   (60,70]   (50,60]  
[190] (70,80]   (30,40]   (70,80]   (40,50]   (40,50]   (50,60]   (60,70]  
[197] (50,60]   (30,40]   (20,30]   (50,60]   (60,70]   (50,60]   (60,70]  
[204] (30,40]   (10,20]   (50,60]   (40,50]   (60,70]   (60,70]   (40,50]  
[211] (30,40]   (30,40]   (30,40]   (50,60]   (50,60]   (40,50]   (50,60]  
[218] (80,90]   (50,60]   (40,50]   (50,60]   (70,80]   (50,60]   (60,70]  
[225] (40,50]   (80,90]   (40,50]   (20,30]   (80,90]   (70,80]   (50,60]  
[232] (30,40]   (40,50]   (60,70]   (70,80]   (70,80]   (60,70]   (40,50]  
[239] (70,80]   (40,50]   (40,50]   (60,70]   (70,80]   (30,40]   (50,60]  
[246] (40,50]   (70,80]   (40,50]   (40,50]   (60,70]   (80,90]   (70,80]  
[253] (80,90]   (60,70]   (80,90]   (80,90]   (80,90]   (50,60]   (100,110]
[260] (60,70]   (80,90]   (50,60]   (30,40]   (80,90]   (20,30]   (30,40]  
[267] (10,20]   (60,70]   (40,50]   (60,70]   (50,60]   (40,50]   (40,50]  
[274] (50,60]   (30,40]   (60,70]   (60,70]   (40,50]   (50,60]   (10,20]  
[281] (40,50]   (80,90]   (30,40]   (80,90]   (60,70]   (50,60]   (70,80]  
[288] (60,70]   (50,60]   (60,70]   (30,40]   (80,90]   (50,60]   (10,20]  
[295] (60,70]   (70,80]   (50,60]   (70,80]   (50,60]   (70,80]   (70,80]  
[302] (50,60]   (70,80]   (20,30]   (90,100]  (30,40]   (30,40]   (50,60]  
[309] (70,80]   (80,90]   (120,130] (80,90]   (30,40]   (80,90]   (30,40]  
[316] (40,50]   (90,100]  (40,50]   (50,60]   (60,70]   (50,60]   (60,70]  
[323] (50,60]   (30,40]   (50,60]   (70,80]   (70,80]   (70,80]   (50,60]  
[330] (60,70]   (50,60]   (60,70]   (80,90]   (70,80]   (60,70]   (20,30]  
[337] (80,90]   (40,50]   (40,50]   (30,40]   (50,60]   (50,60]   (40,50]  
[344] (60,70]   (60,70]   (80,90]   (70,80]   (80,90]   (110,120] (50,60]  
[351] (30,40]   (60,70]   (30,40]   (40,50]   (70,80]   (80,90]   (30,40]  
[358] (60,70]   (30,40]   (60,70]   (80,90]   (30,40]   (50,60]   (70,80]  
[365] (70,80]   (110,120] (40,50]   (30,40]   (80,90]   (30,40]   (60,70]  
[372] (60,70]   (60,70]   (40,50]   (70,80]   (70,80]   (30,40]   (30,40]  
[379] (10,20]   (80,90]   (30,40]   (60,70]   (60,70]   (70,80]   (50,60]  
[386] (20,30]   (40,50]   (70,80]   (40,50]   (60,70]   (70,80]   (70,80]  
[393] (60,70]   (80,90]   (30,40]   (40,50]   (70,80]   (50,60]   (50,60]  
[400] (40,50]   (80,90]   (40,50]   (40,50]   (80,90]   (50,60]   (70,80]  
[407] (20,30]   (70,80]   (40,50]   (50,60]   (50,60]   (50,60]   (50,60]  
[414] (50,60]   (10,20]   (40,50]   (30,40]   (80,90]   (20,30]   (20,30]  
[421] (70,80]   (20,30]   (70,80]   (10,20]   (40,50]   (80,90]   (40,50]  
[428] (40,50]   (40,50]   (50,60]   (40,50]   (40,50]   (60,70]   (40,50]  
[435] (60,70]   (70,80]   (50,60]   (40,50]   (90,100]  (90,100]  (70,80]  
[442] (40,50]   (50,60]   (20,30]   (70,80]   (20,30]   (60,70]   (80,90]  
[449] (50,60]   (10,20]   (60,70]   (50,60]   (40,50]   (40,50]   (60,70]  
[456] (50,60]   (50,60]   (110,120] (40,50]   (40,50]   (40,50]   (50,60]  
[463] (30,40]   (70,80]   (30,40]   (100,110] (60,70]   (70,80]   (60,70]  
[470] (40,50]   (40,50]   (70,80]   (40,50]   (20,30]   (50,60]   (40,50]  
[477] (40,50]   (50,60]   (70,80]   (90,100]  (50,60]   (60,70]   (70,80]  
[484] (50,60]   (70,80]   (50,60]   (70,80]   (60,70]   (90,100]  (50,60]  
[491] (80,90]   (30,40]   (70,80]   (50,60]   (30,40]   (50,60]   (70,80]  
[498] (70,80]   (70,80]   (40,50]   (110,120] (50,60]   (40,50]   (60,70]  
[505] (50,60]   (50,60]   (70,80]   (60,70]   (100,110] (40,50]   (60,70]  
[512] (40,50]   (110,120] (70,80]   (60,70]   (60,70]   (70,80]   (40,50]  
[519] (40,50]   (30,40]   (50,60]   (50,60]   (30,40]   (80,90]   (50,60]  
[526] (70,80]   (60,70]   (30,40]   (50,60]   (70,80]   (50,60]   (40,50]  
[533] (60,70]   (50,60]   (40,50]   (50,60]   (50,60]   (70,80]   (60,70]  
[540] (60,70]   (60,70]   (90,100]  (60,70]   (50,60]   (10,20]   (80,90]  
[547] (40,50]   (40,50]   (60,70]   (60,70]   (40,50]   (40,50]   (50,60]  
[554] (90,100]  (70,80]   (50,60]   (70,80]   (50,60]   (0,10]    (70,80]  
[561] (40,50]   (10,20]   (70,80]   (50,60]   (50,60]   (50,60]   (80,90]  
[568] (40,50]   (40,50]   (80,90]   (70,80]   (80,90]   (80,90]   (40,50]  
[575] (70,80]   (60,70]   (70,80]   (80,90]   (50,60]   (50,60]   (30,40]  
[582] (30,40]   (60,70]   (40,50]   (50,60]   (70,80]   (70,80]   (70,80]  
[589] (30,40]   (70,80]   (50,60]   (50,60]   (90,100]  (40,50]   (40,50]  
[596] (60,70]   (30,40]   (10,20]   (80,90]   (80,90]   (40,50]   (50,60]  
[603] (50,60]   (50,60]   (70,80]   (70,80]   (60,70]   (70,80]   (30,40]  
[610] (50,60]   (30,40]   (40,50]   (40,50]   (50,60]   (90,100]  (30,40]  
[617] (90,100]  (50,60]   (80,90]   (50,60]   (60,70]   (40,50]   (50,60]  
[624] (50,60]   (50,60]   (50,60]   (50,60]   (80,90]   (60,70]   (40,50]  
[631] (70,80]   (60,70]   (80,90]   (60,70]   (40,50]   (70,80]   (0,10]   
[638] (40,50]   (50,60]   (60,70]   (60,70]   (80,90]   (40,50]   (10,20]  
[645] (70,80]   (60,70]   (80,90]   (70,80]   (80,90]   (60,70]   (40,50]  
[652] (30,40]   (70,80]   (50,60]   (0,10]    (40,50]   (40,50]   (50,60]  
[659] (50,60]   (20,30]   (50,60]   (70,80]   (60,70]   (60,70]   (80,90]  
[666] (40,50]   (50,60]   (50,60]   (90,100]  (60,70]   (80,90]   (80,90]  
[673] (80,90]   (70,80]   (100,110] (90,100]  (40,50]   (60,70]   (30,40]  
[680] (50,60]   (50,60]   (10,20]   (70,80]   (80,90]   (30,40]   (60,70]  
[687] (60,70]   (70,80]   (50,60]   (50,60]   (50,60]   (30,40]   (30,40]  
[694] (40,50]   (60,70]   (70,80]   (50,60]   (70,80]   (80,90]   (70,80]  
[701] (70,80]   (70,80]   (40,50]   (80,90]   (50,60]   (50,60]   (40,50]  
[708] (0,10]    (60,70]   (30,40]   (30,40]   (50,60]   (70,80]   (40,50]  
[715] (40,50]   (70,80]   (30,40]   (120,130]
13 Levels: (0,10] (10,20] (20,30] (30,40] (40,50] (50,60] (60,70] ... (120,130]</code></pre>
</div>
</div>
<p>The observations have now been grouped to the classes. You can see this explicitly in the data viewer:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(air_quality_data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>What have we done here?</strong> The first value under the <code>NO2_est</code> column is <strong>61</strong>, this value falls between <strong>61-70</strong> and hence under the <code>Group</code> column is was classed into the <code>(60,70]</code> interval by the <code>cut()</code> function. The second value in <code>NO2_est</code> is <strong>59</strong>, and hence it was classed into the <code>(50,60]</code> interval, and so on. Note that the interval <code>(60, 70]</code> is the equivalent of saying: <strong>“any numbers greater than <code>60</code> (i.e., from <code>60.01</code> onwards but excluding <code>60</code> from that interval), and at the same time being less than or equal to <code>70</code>, inclusively”</strong>. The round bracket <code>(</code> represents any number greater than <code>60</code>, whilst the square bracket <code>]</code> closes the interval translating to any number being less than or equal <code>70</code> at the same time.</p>
</div>
</div>
</section>
<section id="computing-the-frequency-distribution-table-length-002753" class="level3" data-number="1.4.2">
<h3 data-number="1.4.2" class="anchored" data-anchor-id="computing-the-frequency-distribution-table-length-002753"><span class="header-section-number">1.4.2</span> Computing the Frequency Distribution Table (Length: 00:27:53)</h3>
<div class="cell" data-warnings="false">
<div class="cell-output-display">
<div class="vembedr" align="center">
<div>
<iframe src="https://www.youtube.com/embed/YPoGo74MWTY" width="711" height="400" frameborder="0" allowfullscreen="" data-external="1"></iframe>
</div>
</div>
</div>
</div>
<p><a href="https://youtu.be/YPoGo74MWTY">[<strong>Watch on YouTube</strong>]</a></p>
<p>We can now generate our <strong>Frequency Table</strong> and hence determine <strong>Frequency</strong> and <strong>Cumulative Frequency</strong> of the ambient levels of NO<span class="math inline">\(_2\)</span> in Eixample. We perform by using the <code>table()</code> function to tabulate the frequency of values that were grouped within an interval using the <code>Group</code> column.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(air_quality_data<span class="sc">$</span>Groups)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   (0,10]   (10,20]   (20,30]   (30,40]   (40,50]   (50,60]   (60,70]   (70,80] 
        6        17        24        68       131       137       109       116 
  (80,90]  (90,100] (100,110] (110,120] (120,130] 
       72        20         7         7         4 </code></pre>
</div>
</div>
<p>Using <code>table()</code> function only shows results in the Console - lets store the table results in a <strong>data frame</strong> object and call it <code>frequency_results</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>frequency_results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="fu">table</span>(air_quality_data<span class="sc">$</span>Groups))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>frequency_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Var1 Freq
1     (0,10]    6
2    (10,20]   17
3    (20,30]   24
4    (30,40]   68
5    (40,50]  131
6    (50,60]  137
7    (60,70]  109
8    (70,80]  116
9    (80,90]   72
10  (90,100]   20
11 (100,110]    7
12 (110,120]    7
13 (120,130]    4</code></pre>
</div>
</div>
<p>You can see column names <code>Var1</code> and <code>Freq</code>. The <code>Var1</code> is the original <code>Groups</code> columns which incidentally been renamed to <code>Var1</code>. The <code>Freq</code> column was generated from the <code>table()</code> function. We can rename the 1st and 2nd columns using <code>colnames()</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># rename first column t9 "Groups"</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># rename second column to "Frequency"</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># print new variable names in console using names() function</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(frequency_results)[<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="st">"Groups"</span>    </span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(frequency_results)[<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="st">"Frequency"</span> </span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(frequency_results) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Groups"    "Frequency"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>frequency_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Groups Frequency
1     (0,10]         6
2    (10,20]        17
3    (20,30]        24
4    (30,40]        68
5    (40,50]       131
6    (50,60]       137
7    (60,70]       109
8    (70,80]       116
9    (80,90]        72
10  (90,100]        20
11 (100,110]         7
12 (110,120]         7
13 (120,130]         4</code></pre>
</div>
</div>
<p>Finally, we derive the <strong>Relative Frequency</strong> i.e., a percentage that is derived by dividing each frequency value from a group by the total number of observations (i.e., in this case: 718). We can add the <code>relativeFreq</code> column to the <code>frequency_results</code> table.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate a new column</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>frequency_results<span class="sc">$</span>relativeFreq <span class="ot">&lt;-</span> frequency_results<span class="sc">$</span>Frequency<span class="sc">/</span><span class="dv">718</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Interpretation of frequency</strong>: The above table output show the frequency distribution of a set of concentrations for Nitrogen Dioxide measured in Eixample (in Barcelona). The group with the highest frequency value is <code>50-60ppb</code> (i.e., 137) which accounts for <strong>0.1908 (19.08%)</strong> of the data. These measurements typically fall under the category that’s considered to cause moderate harm to humans.</p>
</div>
</div>
<p>Let’s add the <strong>Cumulative Frequency</strong> and <strong>Cumulative Relative Frequency</strong> i.e., percentage using this cumulative summation code i.e., <code>cumsum</code> function below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># add cumulativeFreq column to the data frame by adding Frequency using cumsum() function</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>frequency_results<span class="sc">$</span>cumulativeFreq <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(frequency_results<span class="sc">$</span>Frequency)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># add cumulativeRelFreq column to the data frame by adding Frequency using cumsum() function</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>frequency_results<span class="sc">$</span>cumulativeRelFreq <span class="ot">&lt;-</span> <span class="fu">cumsum</span>(frequency_results<span class="sc">$</span>relativeFreq)</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a><span class="co"># print table results</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>frequency_results</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Groups Frequency relativeFreq cumulativeFreq cumulativeRelFreq
1     (0,10]         6  0.008356546              6       0.008356546
2    (10,20]        17  0.023676880             23       0.032033426
3    (20,30]        24  0.033426184             47       0.065459610
4    (30,40]        68  0.094707521            115       0.160167131
5    (40,50]       131  0.182451253            246       0.342618384
6    (50,60]       137  0.190807799            383       0.533426184
7    (60,70]       109  0.151810585            492       0.685236769
8    (70,80]       116  0.161559889            608       0.846796657
9    (80,90]        72  0.100278552            680       0.947075209
10  (90,100]        20  0.027855153            700       0.974930362
11 (100,110]         7  0.009749304            707       0.984679666
12 (110,120]         7  0.009749304            714       0.994428969
13 (120,130]         4  0.005571031            718       1.000000000</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Thoughts to self</strong>: <code>cumsum</code> function… like WTF man?!</p>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Interpretation of cumulative frequency</strong>: The above table output show the cumulative frequency distribution ambient concentrations for Nitrogen Dioxide measured in Eixample (in Barcelona). We can see that there are 246 measurements or less with N0<span class="math inline">\(_2\)</span> concentrations to be considered as negligible or low impact to health (<code>&lt;50ppb</code>). This corresponds to <strong>0.3426 (34.26%)</strong> of the data.</p>
<p>Conversely, we can also say - we can see that there are 472 measurements with N0<span class="math inline">\(_2\)</span> concentrations more than <code>50ppb</code> which is considered to be moderate or high impact to human health. This corresponds to <strong>0.6573 (65.73%)</strong> of the data.</p>
</div>
</div>
</section>
<section id="graphical-representation-of-frequency-data" class="level3" data-number="1.4.3">
<h3 data-number="1.4.3" class="anchored" data-anchor-id="graphical-representation-of-frequency-data"><span class="header-section-number">1.4.3</span> Graphical Representation of Frequency Data</h3>
<p>The frequency table for <strong>Frequencies</strong> and <strong>Cumulative Frequencies</strong> can be graphical represented in a form of <strong>Histogram</strong> and <strong>Cumulative Frequency Plot</strong> (or <strong>Ogive Plot</strong>) respectively. Now, the data we need must be in its original form (i.e., not grouped) to plot the histogram, and we will need to use the <code>classes</code> object which we created earlier on from the <code>seq()</code> function so as to be used as <code>breaks</code> in the <code>hist()</code> plot function:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(air_quality_data<span class="sc">$</span>NO2_est, <span class="at">breaks =</span> classes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-frequency_distribution_files/figure-html/histogramPlot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The above graph is not to the expected standards! It is missing key details such as the title and label for the x-axis. Let’s apply some cosmetics such as a main title and label for the x-axis</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(air_quality_data<span class="sc">$</span>NO2_est, <span class="at">breaks =</span> classes, <span class="at">main =</span> <span class="st">"Histogram for NO2 in Barcelona"</span>, <span class="at">xlab =</span> <span class="st">"NO2 estimates (ppb)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-frequency_distribution_files/figure-html/histogram_cosmetics-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Interpretation of histogram</strong>: The above figure output describes the shape for ambient measures of NO<span class="math inline">\(_2\)</span> in Barcelona which appears bell-shaped centered around 60ppb. Note that the frequency bars in this graph are essentially the same as the frequency values in the table.</p>
</div>
</div>
<p>Lastly, we then compute its cumulative frequency with the <code>cumsum()</code> function to support the interpretation. The coding needs a bit of hacking because we need to force a starting zero element for this graph to work.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>cumulfreq0 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">cumsum</span>(frequency_results<span class="sc">$</span>Frequency))</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(classes, cumulfreq0)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-frequency_distribution_files/figure-html/cumsum_plot-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Apply the appropriate cosmetics to output by adding the following:</p>
<ul>
<li>Main title</li>
<li>Axis titles for x- and y-axis</li>
<li>Connecting the points to form a full cumulative frequency/ogive plot</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>cumulfreq0 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">cumsum</span>(frequency_results<span class="sc">$</span>Frequency))</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(classes, cumulfreq0, <span class="at">main=</span><span class="st">"Cumulative Frequency for N02 in Barcelona"</span>, <span class="at">xlab=</span><span class="st">"NO2 estimates (ppb)"</span>, <span class="at">ylab=</span><span class="st">"Cumulative Frequencies"</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(classes, cumulfreq0) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="04-frequency_distribution_files/figure-html/cumsum_cosmetics-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./03-handling_data_structures.html" class="pagination-link" aria-label="Week 2: Introduction II">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Week 2: Introduction II</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/UCLPG-MSC-SGDS/GEOG0186/issues/new" class="toc-action"><i class="bi bi-github"></i>Report an issue</a></li></ul></div></div></div></footer><script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>